//POST https://suporteformacaodev.app.n8n.cloud/webhook/assistente-pessoal
Content-Type: application/json

{
  "chatId": "12345678",
  "mensagem": "Você trabalha com React Native?"
} 

// aqui precisa ser feito a conexão com o N8N.